[EDIT] 상세페이지 조회 데이터 추가
wecode-bootcamp-korea/36-2nd-Winnerest-backend pull request #17
Opened 2022-09-06 09:23 UTC by Seongmin-Gil

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [x] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 프론트 요청에 따라 상세페이지 조회 기능에 리뷰 카운터 데이터 추가

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 쿼리문을 이용하여 해당 핀에 대한 리뷰를 카운트하여 코드 추가

2022-09-06 09:35 UTC, bigfanoftim requested changes

2022-09-06 09:35 UTC, bigfanoftim commented on controllers/boardController.js
> +    res.status(204).json({message : 'DELETE_BOARD'});
이거 response body 잘 출력되는지 확인해보셨나요?

2022-09-06 09:41 UTC, Seongmin-Gil commented on controllers/boardController.js
> +    res.status(204).json({message : 'DELETE_BOARD'});
204는 삭제 statusCode여서 출력이 안되는 걸로 알아서 처음에 .json을 추가하지 않았는데 해당 부분을 추가하지 않으니 클라이언트 쪽에서 응답 대기 상태로 돌아가서 해당 부분을 추가하였습니다.

2022-09-07 01:57 UTC, bigfanoftim commented on controllers/boardController.js
> +    res.status(204).json({message : 'DELETE_BOARD'});
`res.status(204).end()`로도 아마 동작할겁니다! 이 부분은 항상 유의해주세요~

2022-09-07 01:58 UTC, bigfanoftim approved these changes
LGTM 👍

2022-09-07 01:58 UTC, merged