ADD: 카카오 로그인 구현 & error handler 구현
wecode-bootcamp-korea/36-2nd-Winnerest-backend pull request #3
Opened 2022-09-01 02:25 UTC by sk8ilar

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 아이디, 비밀번호 입력창을 사용한 로그인 기능 구현 (예시)

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
카카오 로그인 구현 
프론트한테 토큰 발급 받으면, 그 토큰 가지고 카카오 서버에 통신해서 사용자 정보 받아왔습니다
이때 유저가 회원가입 된 유저면, database에 유저의 정보를 저장하고 토큰 보내주고
회원가입이 안된 유저면 그냥 토큰만 보내줬습니다.

추가적으로 error handler도 한번에 구현해 봤습니다.!

unit test까지는 아직 하지를 못해서 pr부터 올려봤습니다.
<br />

2022-09-01 08:12 UTC, bigfanoftim requested changes
전체적으로 구현에 급급한 상태로 코드를 작성한듯 보입니다. 구현도 물론 중요하지만 더 중요한 것은 `얼마나 좋은 코드를 쓰냐` 입니다. 기업협업 혹은 취준 기간(기업 과제) 동안 계속해서 남들에게 코드를 보여줘야 할 일이 많을텐데 지금 습관이 잘못들어져 있으면 생각보다 고치기가 쉽지 않을 것입니다.

계속해서 더 좋은 코드를 작성하는데 집중해주세요@!

2022-09-01 08:12 UTC, bigfanoftim commented on controllers/authController.js
> +        const accessToken = headers.split(" ")[1];
split의 목적이 혹시 불필요한 부분을 떼어내기 위함이라면 애초에 client로부터 필요한 데이터만 받아야 할 것 같습니다.
모든걸 감안하고 작성한다해도 
```JavaScript
const accessToken = req.headers.authorization.split(" ")[1];
```
이렇게 적는게 더 효율적이겠네요!

2022-09-01 08:12 UTC, bigfanoftim commented on controllers/authController.js
> +            })
```suggestion
       const response = await fetch("https://kapi.kakao.com/v2/user/me")
```
then으로 계속해서 콜백으로 코드를 늘려쓰면 가독성이 좋지 않습니다. 한번 다음과 같이 작성하여 활용해 보시겟어요?

2022-09-01 08:12 UTC, bigfanoftim commented on middlewares/auth.js
> +    const accessToken = headers.split(" ")[1];
여기도 마찬가지입니다.

2022-09-01 08:12 UTC, bigfanoftim commented on middlewares/auth.js
> +  }
어차피 다음 미들웨어로 넘기는 코드를 만드신것 같은데 try catch가 필요한가요?

2022-09-01 08:12 UTC, bigfanoftim commented on middlewares/errorHandler.js
> +                res.status(err.statusCode ? err.statusCode : 400).json({ message: err.message });
key error만 분기처리하는 이유가 무엇인가요? 해당 에러는 애초에 컨트롤러 레이어에서 statusCode와 message를 만들어 넘기지 않나요?

2022-09-01 08:12 UTC, bigfanoftim commented on models/authDao.js
> +const getUserById = async (kakaoId) => {
```suggestion
const getUserByKakaoId = async (kakaoId) => {
```
id가 아니라 kakao_id로 필터링중이니 명확히 적어주세요.

2022-09-01 08:12 UTC, bigfanoftim commented on models/dataSource.js
> +  });
unittest 자료 보시고 app.js와 server.js로 분리해 주시고 그에맞게 이니셜라이징하는 함수도 위치에 맞게 수정해 주세요

2022-09-01 08:12 UTC, bigfanoftim commented on routes/authRouter.js
> +authRouter.get("/logIn", errorHandler(authController.logIn));
```suggestion
authRouter.get("/kakao-login", errorHandler(authController.logIn));
```
확장성을 고려해서라도 정확하게 작성해주세요!

2022-09-01 08:12 UTC, bigfanoftim commented on services/authService.js
> +      return jwt.sign({ sub: user.insertId, exp: Math.floor(Date.now()/1000) + (600*600) }, process.env.JWT_SECRET);
`jwt.sign`이라는 똑같은 함수가 들어가는 value만 다른채로 반복되고 있네요 줄일 수 있는 방안을 찾아보시면 좋겟습니다.

2022-09-01 12:15 UTC, sk8ilar commented
> 전체적으로 구현에 급급한 상태로 코드를 작성한듯 보입니다. 구현도 물론 중요하지만 더 중요한 것은 `얼마나 좋은 코드를 쓰냐` 입니다. 기업협업 혹은 취준 기간(기업 과제) 동안 계속해서 남들에게 코드를 보여줘야 할 일이 많을텐데 지금 습관이 잘못들어져 있으면 생각보다 고치기가 쉽지 않을 것입니다.
> 
> 계속해서 더 좋은 코드를 작성하는데 집중해주세요@!

넵 피드백 감사합니다!! 제가 코드를 조금 날것으로? 짜는 것 같은데 최대한 중복되지 않게 신경써서 짜도록 노력하겠습니다!

2022-09-02 01:44 UTC, bigfanoftim requested changes

2022-09-02 01:44 UTC, bigfanoftim commented on controllers/authController.js
> +    const accessToken = req.headers.authorization.split(" ")[1];
<img width="680" alt="image" src="https://user-images.githubusercontent.com/62135254/188039005-18ed9ed5-3e48-4989-965f-93b16be6bf34.png">

2022-09-02 01:44 UTC, bigfanoftim commented on controllers/authController.js
> +    const accessToken = req.headers.authorization.split(" ")[1];
split을 쓸 필요가 없지만 설령 쓰더라도 아래와 같이 수정하는 것이 더 좋겠다는 리뷰였습니다. 따라서 아래와 같이 수정하는게 아니라 split을 쓸 필요가 없으니 더 개선할 점을 찾아야겠죠?

split을  쓰는 이유가 공백을 기준으로 두개의 문자열을 받는 것 같은데 애초에 필요한 데이터만 전달받으면 되는데 굳이 불필요한 데이터를 받아서 분석할 필요는 없어보입니다. [0]의 스트링은 전혀 활용되지 않으니까요!

만약 꼭 필요한 상황이라면 해당 PR에 커멘트 남겨주세요!

2022-09-02 01:44 UTC, bigfanoftim commented on controllers/authController.js
> +        const Token = await authService.logIn(nickname, kakaoId, profileImgUrl)
```suggestion
```
토큰은 클래스가 아닙니다. 네이밍 컨벤션 지켜주세요!

2022-09-02 01:44 UTC, bigfanoftim commented on middlewares/auth.js
> +    const accessToken = req.headers.authorization.split(" ")[1];
여기도 마찬가지입니다.

2022-09-02 01:44 UTC, bigfanoftim commented on middlewares/auth.js
> +};
이 부분은 다른 PR에 남긴 리뷰를 확인해보시면 아시겠지만 이 PR이 늦어지면 늦어질수록 다른 곳에서 활용하지 못합니다. 이 부분만 따로 분리하던지 해야 할 것 같아요.

2022-09-02 01:44 UTC, bigfanoftim commented on middlewares/auth.js
> +      throw new error("USER_NOT_DEFINED",409)
```suggestion
      throw new error("USER_NOT_DEFINED",409)
```
status code 다시 확인해주세요.

2022-09-02 01:44 UTC, bigfanoftim commented on controllers/authController.js
> +const error = require("../middlewares/errorCreater");
error 가 정확한 명칭이 아닙니다 네이밍한대로 정확하게 가져와주세요! 이러면 Error와 헷갈릴 수 있습니다.

2022-09-02 01:44 UTC, bigfanoftim commented on models/authDao.js
> +const error = require("../middlewares/errorCreater");
여기도 네이밍 확인해주세요

2022-09-02 01:44 UTC, bigfanoftim commented on server.js
> +require("dotenv").config();
혹시 이 코드가 없으면 실행이 안되던가요?

2022-09-02 01:44 UTC, bigfanoftim commented on services/authService.js
> +    const jwtSign = {sub: user.insertId, exp: Math.floor(Date.now()/1000) + (600*600)}
user가 생성이 되지 않았을때 `user.insertId` 가 undefined가 나지 않나요?

테스트가 제대로 되지 않은채로 PR이 올라왔습니다.ㅠㅠ

2022-09-02 01:44 UTC, bigfanoftim commented on services/authService.js
> +  };
`jwt.sign`이 두번이나 중복되니 해결해달라는 리뷰였는데 아직도 두개네요?ㅠㅠ

만약 해결이 잘 되지 않거나 파악이 잘되지 않는다면 PR에 커멘트를 통해서 커뮤니케이션 해주세요!

```JavaScript
let user = await getUser(..)

if (!user) {
  result = await createUser(..)

  user = await getUser(...result.InsertId)
}

return jwt.sign(user.id, ..)
```

dao를 한 번 더 호출하는 것이 찝찝한 경우

```JavaScript
let user = await getUser(..)

if (!user) {
  result = await createUser(..)

  user = { id: result.insertId }
}

return jwt.sign(user.id, ..)
```

이렇게 해볼 수 있겠네요. 하지만 후자의 방법보다 전자의 방법으로 하는 것이 코드 가독성이 훌륭합니다.

2022-09-02 08:45 UTC, bigfanoftim commented
다른 PR로 나누신 내용 제외하고 PR명이랑 코드 다시 수정해 주세요~

여기에 작성한 코드들이 맨위에 PR이 빠르게 머지되어야 구동되는 코드들이라 PR은 그대로 남겨놓겠습니다~ 고생하셨어요!

2022-09-02 14:44 UTC, bigfanoftim requested changes

2022-09-02 14:44 UTC, bigfanoftim commented on controllers/authController.js
> +            throw new ErrorCreater("KEY_ERROR", 400)}
```suggestion
```
이 부분도 전부 `authService.logIn`에 넣어 주세요!

2022-09-05 01:47 UTC, bigfanoftim approved these changes
LGTM 👍

2022-09-05 01:47 UTC, merged