[ADD] 메인페이지 Pin 조회 API End-Point 구현
wecode-bootcamp-korea/36-2nd-Winnerest-backend pull request #4
Opened 2022-09-01 07:29 UTC by Seongmin-Gil

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [X] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 메인페이지 pin 조회 기능 API End-Point 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 로그인한 유저에 대한 ID 정보를 토큰에서 받어 해당 유저가 등록한 pin과 같은 tag들에 대한 pin들을 메인페이지에서 보여지는 기능을 구현하였습니다.
 - Unit test를 통해 조회 성공 시 200번 Status Code가 나오는 것을 확인하였습니다.
 - Postman 도구를 이용하여 서버 정상 작동 및 데이터 정상 출력 확인

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 동일한 테그를 가지고 있는 pin을 모두 출력하였지만, 추후 LIMIT 문을 이용하여 전송되는 데이터의 양을 줄일 수 있도록 하겠습니다.
- 로그인 API가 merge되면 JWT 관련 코드를 받아서 추가하도록 하겠습니다.

2022-09-01 08:13 UTC, bigfanoftim commented
> 로그인 API가 merge되면 JWT 관련 코드를 받아서 추가하도록 하겠습니다.

로그인 API의 머지가 길어지면 JWT 관련 코드를 해당 API에 적용할 수 없으니 auth 관련 미들웨어를 따로 PR로 작성하여 빠르게 적용하는 방향으로 진행해주세요.

2022-09-01 08:17 UTC, bigfanoftim requested changes
또 다른 PR에 있는 내용이 왜 여기에도 있네요. 이러면 불필요한 공수를 들여 시간을 낭비하신게 됩니다..

애초에 동시에 사용될만한 코드였다면 따로 분리해서 PR을 작성해서 빠르게 리뷰와 머지받아주세요!

2022-09-05 07:55 UTC, bigfanoftim requested changes

2022-09-05 07:55 UTC, bigfanoftim commented on controllers/pinController.js
> +    const userId = user.id
```suggestion
    const userId = req.user.id
```

2022-09-05 07:55 UTC, bigfanoftim commented on models/pinDao.js
> +            WHERE board.user_id = ?)
이 Where절이 없으면 동작하지 않나요?

2022-09-05 07:55 UTC, bigfanoftim commented on routes/index.js
> +router.use('/pins', pinRouter.router)
이왕이면 auth에서 사용한 방식과 통일해주세요~
```suggestion
router.use('/pins', pinRouter)
```

2022-09-05 07:55 UTC, bigfanoftim commented on routes/pinRouter.js
> +router.get('/main', errorHandler(auth.validationToken), errorHandler(pinController.findMainPins));
```suggestion
// 페이지 단위로 개발하지 않습니다!
// main이라고 써버리면 네이밍에 의해서 main 페이지에 제한되는 것처럼 보여집니다.
router.get('', errorHandler(auth.validationToken), errorHandler(pinController.findMainPins));
```

2022-09-05 08:57 UTC, Seongmin-Gil commented on controllers/pinController.js
> +    const userId = user.id
해당 사항 반영하여 수정완료하였습니다.

2022-09-05 08:57 UTC, Seongmin-Gil commented on routes/index.js
> +router.use('/pins', pinRouter.router)
auth 방식과 통일하여 수정하였습니다.

2022-09-05 08:57 UTC, Seongmin-Gil commented on routes/pinRouter.js
> +router.get('/main', errorHandler(auth.validationToken), errorHandler(pinController.findMainPins));
해당 사항 반영하였습니다.

2022-09-05 08:59 UTC, Seongmin-Gil commented on models/pinDao.js
> +            WHERE board.user_id = ?)
메인 페이지에 조회되는 pin들은 해당 유저가 작성한 핀들과 같은 tag를 가지고 있는 핀들만 조회하는 기능을 가지고 있어서 서브쿼리를 사용하여 유저가 가지고 있는 핀들의 tag목록을 가지고와서 Where 문으로 제한을 걸게 되었습니다.

2022-09-06 02:12 UTC, bigfanoftim approved these changes
LGTM 👍

2022-09-06 02:12 UTC, merged