[ADD] Board 생성 기능 END-POINT 구현
wecode-bootcamp-korea/36-2nd-Winnerest-backend pull request #7
Opened 2022-09-05 07:02 UTC by Seongmin-Gil

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [X] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 유저 Board 생성 기능 API END-POINT 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 토큰을 통해 유저 정보 확인 및 Board 생성

2. Unit Test를 통해 설정 오류에 따른 Status Code 및 메시지 반환 확인

3. PostMan을 통해 서버 정상 작동 여부 확인

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- mysql에서 외래키에 ON DELETE CASCADE 설정을 통하여 해당 보드에 소속된 핀 게시글도 함께 삭제되도록 설정하였습니다.

2022-09-05 08:03 UTC, bigfanoftim requested changes

2022-09-05 08:03 UTC, bigfanoftim commented on .env.test
> +TYPEORM_DATABASE=jestDB
```suggestion
```
config는 전부 gitignore에 추가해 주세요. 이미 한 번 커밋된 내역은 `git rm --cache` 명령어를 통해서 해결해보세요!

2022-09-05 08:03 UTC, bigfanoftim commented on db/migrations/20220905062604_alter_fk_board.sql
> +ON DELETE CASCADE;
db 마이그레이션은 다른 PR로 분리해서 빠르게 머지받아 주세요. 다른 코드 리뷰받느라 늦어지면 해당 db 수정 사항을 팀 내에서 적용하지 못한채로 개발하게 됩니다!

2022-09-05 08:03 UTC, bigfanoftim commented on models/boardDao.js
> +    }
try 블록 내에서 발생한 모든에러가 data input이 잘못되어 발생하는 에러는 아닙니다. 어차피 errorHandler 메소드로 에러를 캐치해줄 것 같은데 그걸로 충분해 보입니다. 이게 이해가 안되시면 바로 찾아와 주세요.

2022-09-05 08:03 UTC, bigfanoftim commented on test/createBoard.test.js
> +        expect(res.status).toEqual(400);
```suggestion
        const res = await request(app)
            .post('/board')
            .set({ Authorization: 'Some Random Token' })
            .expect({ message : 'KEY_ERROR' })
            .expect(400)
```

결과를 받아서 expect로 비교할 것인지. 아니면 바로 .expect()를 통해 바로 비교할 것인지 하나로 통일해 주세요.

모든 테스트 코드에 해당하는 코멘트이니 전부 적용해 주세요!

2022-09-05 09:34 UTC, Seongmin-Gil commented on .env.test
> +TYPEORM_DATABASE=jestDB
브랜치 변경하면서 해당 내용이 반영이 되지않았던거 같습니다. 수정하였습니다.

2022-09-05 09:34 UTC, Seongmin-Gil commented on db/migrations/20220905062604_alter_fk_board.sql
> +ON DELETE CASCADE;
따로 분리해서 PR 올리도록 하겠습니다.

2022-09-05 09:34 UTC, Seongmin-Gil commented on models/boardDao.js
> +    }
이해하였습니다. 해당 사항 반영하여 수정하였습니다.

2022-09-05 09:35 UTC, Seongmin-Gil commented on test/createBoard.test.js
> +        expect(res.status).toEqual(400);
.expect() 로 통일하여 반영하였습니다.

2022-09-06 02:47 UTC, bigfanoftim approved these changes
LGTM 👍

2022-09-06 02:47 UTC, merged