ADD: pin 업로드 기능 구현
wecode-bootcamp-korea/36-2nd-Winnerest-backend pull request #9
Opened 2022-09-05 16:58 UTC by sk8ilar

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
PIN을 업로드하는 기능 구현
1. 키에러와, 유효하지 않은(자신이 만들지 않은 보드)를 선택했을때 에러처리
2. 트랜잭션과 bulk insert를 이용해서 하나의 pin 테이블을 만들고 난 후 추가적으로 pin_tag 테이블을 tag의 갯수만큼 
만들어 준다.
3. 프론트에게 json.stringify로 받은 값을 json.parse로 json화 처리해 준다.

<br />

<br />

## :: 기타 질문 및 특이 사항
- 서버에서 에러처리로 인해 업로드에 실패해도 AWS에는 실제로 사진이 올라가는 현상이 발생합니다. 
- AWS에 업로드 할때와 router -> controller-> service -> dao 여기사이의 순서가 중요할 것 같은데 어디에 처리하는 것이 좋을지 질문하고 싶습니다!

2022-09-06 06:20 UTC, bigfanoftim requested changes
> 서버에서 에러처리로 인해 업로드에 실패해도 AWS에는 실제로 사진이 올라가는 현상이 발생합니다.
AWS에 업로드 할때와 router -> controller-> service -> dao 여기사이의 순서가 중요할 것 같은데 어디에 처리하는 것이 좋을지 질문하고 싶습니다!

우선 api를 활용해서 s3 업로드를 트랜잭션으로 구현하는 것은 불가능합니다. 따라서 그나마 가능하다면 `dao -> s3 upload` 이정도가 있을텐데 이것도 완벽하진 않습니다.

하지만 aws lambda를 이용하면 transaction을 구현할 수 있는 것으로 알고 있습니다.

대신 지금처럼 진행하더라도 dao에서 최대한 실패할 일이 없게 디테일한 예외처리만 해주셔도 충분할 듯 보입니다.

2022-09-06 06:20 UTC, bigfanoftim commented on controllers/pinController.js
> +    const {boardId, title, contents, tagIdsText} = result;
<img width="539" alt="image" src="https://user-images.githubusercontent.com/62135254/188559454-4d0d8c0c-67ca-481b-b2f0-24047708ff05.png">

form-data에서 다른 값을 list로 보내고 싶으면 이런식으로 query parameter를 여러개 보내는 것처럼 하면 됩니다.
그럼 받아온 값을 불필요하게 파싱하는 일은 하지 않아도 됩니다.

2022-09-06 06:48 UTC, sk8ilar commented on controllers/pinController.js
> +    const {boardId, title, contents, tagIdsText} = result;
멘토님 저희 tagIds에는 배열 ex: [1,2,3] 이 들어갈 예정이였는데 배열 같은 경우도 쿼리 파라마터로 보내는 방법이 있나요?

2022-09-06 07:31 UTC, bigfanoftim commented on controllers/pinController.js
> +    const {boardId, title, contents, tagIdsText} = result;
`:3000/products?category_id=1&category_id=2` 이런식으로 보내면 바로 리스트로 받아 쓸 수 있습니다.

2022-09-06 08:17 UTC, sk8ilar commented on controllers/pinController.js
> +    const {boardId, title, contents, tagIdsText} = result;
넵 알겠습니다

2022-09-06 08:26 UTC, sk8ilar commented on controllers/pinController.js
> +    const {boardId, title, contents, tagIdsText} = result;
수정 사항 반영 했습니다.

2022-09-06 09:25 UTC, bigfanoftim requested changes

2022-09-06 09:25 UTC, bigfanoftim commented on modules/multer.js
> +    bucket: 'minseok',
bucket명도 `.env`에서 관리해 주세요.

2022-09-06 09:25 UTC, bigfanoftim commented on routes/pinRouter.js
> +pinRouter.post("/", errorHandler(auth.validationToken), errorHandler(upload.single('imgUrl')),  errorHandler(pinController.createPin))
`multer()`를 미들웨어에 두고 file을 controller로 넘긴 후에 자세한 로직은 service layer에서 관리하는 것이 보다 편할 것 같습니다.

- `multer()`를 미들웨어에 두고 이미지 `next(controller)`로 전달
- `req.file`을 service layer로
- service layer에서 aws-sdk를 활용한 s3 upload 메소드 실행 및 로직들 한 번에 관리

2022-09-07 07:46 UTC, bigfanoftim approved these changes
LGTM 👍

2022-09-07 07:46 UTC, merged